### ISSUE TITLE
Quickstart guide failed

### ISSUE THREAD

**Issue by RorixRebel** [lucianopuccio/golem#25]
Installed it in a virtualenv then i tried to create the folder and i got this.
python 3.5.3

```
(venv) ➜  golem-framework golem-admin createdirectory test
zsh: command not found: golem-admin
```

So i brute forced installed it as sudo and then i got this

```
Traceback (most recent call last):
  File "/usr/local/bin/golem-admin", line 7, in <module>
    from golem.bin.golem_admin import main
  File "/usr/local/lib/python2.7/dist-packages/golem/bin/golem_admin.py", line 6, in <module>
    from .. import commands
  File "/usr/local/lib/python2.7/dist-packages/golem/commands/__init__.py", line 1, in <module>
    from .base import (CommandException, RunCommand,
  File "/usr/local/lib/python2.7/dist-packages/golem/commands/base.py", line 3, in <module>
    from golem.core import (utils,
  File "/usr/local/lib/python2.7/dist-packages/golem/core/__init__.py", line 37
    raise Exception(msg) from None
                            ^
```

Does the guide need to be updated?
if so, let me know so i can help

**Comment by lucianopuccio** [comment]
It seems from the stack trace you are using Python 2.7 inside the virtualenv. 

If you have Python 3 installed, try forcing the version when creating the virtualenv:

```
virtualenv env -p python3
```

Check (https://stackoverflow.com/questions/45293436/how-to-specify-python-version-used-to-create-virtual-environment)

Let me know if that helps. Thanks!

**Comment by RorixRebel** [comment]
yep somehow it was using python 2 even tho i was in a virtualenv for python3...
got it to work. will test it out.
