### ISSUE TITLE
NameError: name 'run_test' is not defined

### ISSUE THREAD

**Issue by danielmaddern** [lucianopuccio/golem#60]
python golem.py run test_project test --environment Local -i                                                                 
Traceback (most recent call last):
  File "golem.py", line 15, in <module>
    execute_from_command_line(os.getcwd())
  File "/Users/daniel/Development/pythons/golem/lib/python3.6/site-packages/golem/main.py", line 27, in execute_from_command_line
    commands.run(args.main_action, test_execution, args)
  File "/Users/daniel/Development/pythons/golem/lib/python3.6/site-packages/golem/commands/__init__.py", line 51, in run
    cmd.run(tex, args)
  File "/Users/daniel/Development/pythons/golem/lib/python3.6/site-packages/golem/commands/base.py", line 99, in run
    test=test_execution.test)
  File "/Users/daniel/Development/pythons/golem/lib/python3.6/site-packages/golem/test_runner/start_execution.py", line 167, in run_test_or_suite
    run_test(test_execution.root_path, test_execution.project,
NameError: name 'run_test' is not defined

**Comment by lucianopuccio** [comment]
fixed by #61
